services:
    web:
        container_name: ${CONTAINER_NAME}
        build:
            dockerfile: .docker/web/Dockerfile
            context: ..
            args:
                - USERNAME=${USERNAME:-ubuntu}
                - UID=${UID:-1000}
                - GROUP=${GROUP:-root}
                - ROOTPASS=${ROOTPASS:-test}
        expose:
            - "${WEB_PORT:-80}"
        volumes:
            - ../:/var/www
        extra_hosts:
            - host.docker.internal:host-gateway
        links:
            - db
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=${ENTRYPOINT}"
            - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DOMAIN}`, `api.${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}.service=${CONTAINER_NAME}"
            - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=${WEB_PORT:-80}"
        networks:
            - proxy
        tty: true

    db:
        container_name: "${CONTAINER_NAME}-db"
        image: mysql:9.3
        command: --secure-file-priv='' --skip-log-bin
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-test}"
        volumes:
            - ./docker_volumes/db:/var/lib/mysql
            - ./main-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${CONTAINER_NAME}-db.entrypoints=${ENTRYPOINT_DB}"
            - "traefik.http.routers.${CONTAINER_NAME}-db.rule=Host(`db.${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}-db.service=${CONTAINER_NAME}-db"
            - "traefik.http.services.${CONTAINER_NAME}-db.loadbalancer.server.port=${MYSQL_PORT:-3306}"
        networks:
            - proxy

networks:
    proxy:
        external: true
